name: Test on Push
on:
  push:

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
      - name: Run Checkstyle and SpotBugs
        run: ./gradlew check
        working-directory: api
      - name: Test
        run: ./gradlew test
        working-directory: api
      - name: Build
        run: ./gradlew clean assemble
        working-directory: api
